[package]
name = "rs-merk-verify-c-binding"
version = "0.1.1"
edition = "2021"
build = "build.rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.merk]
git = "https://github.com/QuantumExplorer/merk"
branch = "improvement/proofRoot2"
features = ["verify"]
default-features = false


[lib]
name = "merk_ios"
crate-type = ["staticlib"]      # Creates dynamic lib

[build-dependencies]
cbindgen = "0.19"
